services:
  jc2e-tea:
    container_name: jc2e-tea-astro
    build:
      context: ./astro
      target: dev-test
    restart: always
    ports:
      - 1733:1733
      - 1734:1734
    volumes:
      - '.:/jc2e-tea'
